name: GitHub Metrics

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: alfen-yu
          template: classic
          base: header, activity, repositories, metadata
          config_timezone: Asia/Karachi
          repositories_forks: no
          
          # Languages plugin
          plugin_languages: yes
          plugin_languages_limit: 12
          plugin_languages_sections: most-used
          plugin_languages_colors: github
          plugin_languages_threshold: 0%
          plugin_languages_indepth: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_analysis_timeout: 30
          plugin_languages_categories: markup, programming
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_load: 500
          plugin_languages_recent_days: 365
          
          # Traffic plugin
          plugin_traffic: yes
          
          # Output
          filename: github-metrics.svg
          output_action: commit
          committer_message: "chore: update GitHub metrics"